### ISSUE TITLE
NK-15V uses NK-43 model, which is too large.

### ISSUE THREAD

**Issue by TheDestroyerKSP** [KSP-RO/ROEngines#137]
I mentioned this one on the discord but I figured I should keep track of it here. NK-15V/NK-43 uses the NK-43 model which is larger, making it unusable as N1 engine.
[RNs NK-15V](https://cdn.discordapp.com/attachments/663102368887472156/852392484679843870/unknown.png)
[ROEs NK-15V](https://cdn.discordapp.com/attachments/663102368887472156/852392717676838923/unknown.png)

Perhaps the NK-15V/NK-43 need to be split into separate engine parts instead of a config.

**Comment by NathanKell** [comment]
I believe @al2me6 's work on automatic B9PS-with-config in RF can be used here, we can swap between the two models based on the config chosen. @pap1723 do we *have* a NK-15V model?
