### ISSUE TITLE
RD-107-117 and RD-108-118 vernors do not upgrade along with main engine

### ISSUE THREAD

**Issue by fat-lobyte** [KSP-RO/ROEngines#14]
The ROEngines version for the RD-107/108 engines and its derivatives features two different engines:
The main engine and the small vernor engines. While this may seem like a good idea at first, there are two main problems with it:

1. The vernors are not upgraded along with the main engine. This means that the mixture ratios will be incorrect. That's especially problematic for the RD-117/RD-118 variants which use Syntine instead of Kerosene, while the vernors on the same part still use Kerosene
2. The Vernors do not respect ullage and ignition rules, and can be restarted arbitrarily.

Is there a way to simply drop the separate config for the vernors, add vectoring to the main engines and make only the *model* act like the vernor engines are moving?

**Comment by blowfishpro** [comment]
I’m confused.  The ROEngines RD-107/8 include the verniers, they’re not separate parts.  And they only have a single engine module and gimbal module

**Comment by fat-lobyte** [comment]
They're not separate parts, but they clearly behave as separate entities. I guess they're two separate modules or something.

a) The vernors light up first and reach max thrust pretty much instantly, whereas the main engines take longer to spool up.
b) Upgrading the engines to use Syntin (11D512P config) and launching the rocket without kerosene results in the vernors not working
c) Running out of Syntin but not kerosene causes the vernors to continue running while the main engines shut off
d) When trying to start the engine a second time, the main engine (correctly) doesn't start up, but the vernors do.

To clarify: I mean the model that is in the RealEngines pack, not the model that comes from Vens Stock Revamp or from SXT. The latter don' have the separate engines and only have a single engine module and gimbal module. The former has two engine modules.

**Comment by fat-lobyte** [comment]
Here's a screenshot:

![screenshot101](https://user-images.githubusercontent.com/173609/57147703-7d06df80-6dc8-11e9-9e5c-c7e6cbb7bdee.png)

As you can see
a) Main engines are off (TestFlight failure), but vernors are still running
b) Kerosene is draining, Syntin (required for RD-108-11D512P ) is not
c) In the right-click menu, there are two sections for the engine info

**Comment by leudaimon** [comment]
This is not the model that comes with ROEngines, is it? It looks like the one in RealEngines, as you mention above. You shouldn't even have ROEngines installed to have this model available.

**Comment by blowfishpro** [comment]
Yes, that looks like not ROEngines

**Comment by fat-lobyte** [comment]
My bad, I thought that this repository is for RealEngines. So where would I report that?

**Comment by blowfishpro** [comment]
it should be possible to unify the engine modules in the RO configuration (probably the most straightforward place to make the change in this case), someone has to actually take the time to do that though.

**Comment by fat-lobyte** [comment]
@blowfishpro  So should I create an issue in the RealismOverhaul repo?

**Comment by blowfishpro** [comment]
I think so
