### ISSUE TITLE
Is @raidernick's CC-BY-NC-ND license being obeyed?

### ISSUE THREAD

**Issue by HebaruSan** [KSP-RO/ROEngines#140]
From [the forum takedown announcement for the "Buran Energia Mod-Rebalanced and Fixed" mod](https://forum.kerbalspaceprogram.com/index.php?/topic/199703-18-111-buran-energia-mod-rebalanced-and-fixed-rssro-compatible/&do=findComment&comment=3991219):

![image](https://user-images.githubusercontent.com/1559108/122619381-f3710500-d055-11eb-8831-969c6ad44733.png)

This is suggestive that ROEngines may have a licensing problem with some of its content.

Chatting with @raidernick (including here to confirm authorial intent, happy to remove if @raidernick considers publicly sharing these private messages to be a privacy violation):

![image](https://user-images.githubusercontent.com/1559108/122619430-0b488900-d056-11eb-863d-7e8dd787e8fe.png)

This "RN" folder seems to contain @raidernick's content:

- https://github.com/KSP-RO/ROEngines/tree/master/GameData/ROEngines/Assets/RN

I'm not necessarily in the loop on all of the relevant backstory here, so my question is:
Is the ROEngines mod distributing an unauthorized derivative of @raidernick's work?

**Comment by raidernick** [comment]
I want to clarify that I only asked that my pods be removed but I said that the engines they were using were ok. I'm sorry for being vague about what I wanted removed. However, I did state that I want the license for my parts kept the same. I'm told that the most restrictive license for any parts included in a mod is what needs to be used. So at the very least this mod needs to be BY-NC-ND, and possibly ARR depending on the licenses for the other mods included in it. So either way, this mod can't be redistributed as it was in that Buran mod.

**Comment by jwvanderbeck** [comment]
License in the NETKAN has been changes to CC-BY-NC-ND.  By default GH licenses are ARR unless a license file is specified, which one isn't so technically ROEngines is ARR.

That said I will add a license file to GH to indicate CC-BY-NC-ND as well

**Comment by HebaruSan** [comment]
OK, since ROEngines is/became CC-BY-NC-ND and includes the RN content with permission, that would mean the takedown notice should have been phrased slightly differently ("ROEngines does not allow derivatives") and simplifies the situation otherwise (no need to worry about removing from CKAN or other such punitive measures). Thanks for the clariications and updates, I think that's sufficient to close this.

**Comment by HebaruSan** [comment]
@raidernick, FYI, a new version of the Buran Energia mod has just been uploaded. Does it still have licensing problems?

https://spacedock.info/mod/2966/%5B1.8-1.12.x%5D%20Buran%20Energia%20Mod%20-%202.0%20%5BRSS/RO%20Compatible%5D

**Comment by raidernick** [comment]
from a quick look at the files it appears to be ok now...unless they just renamed the files and hid them. I didn't see the blatant theft there this time at first glance.
