### ISSUE TITLE
Misplaced RCS-like engines

### ISSUE THREAD

**Issue by leudaimon** [KSP-RO/ROEngines#15]
I noticed that two of the Niche Parts engines included as small RCS-like engines are misplaced and/or with strange configs.

* The TD-339 is a bipropellant RCS-like engine in the Early landing node. I think it should be in Early Docking Procedures with the other bi-propellant RCS.

* The R-4D is a very advanced (311 isp) RCS-like engine currently in Early Docking Procedures. Its description implies it's from much later, with mentions to Cassini and the Orion Capsule. Also, it has only 1 ignition, which doesn't make much sense for this kind of engine.

**Comment by pap1723** [comment]
Updated, moved TD-339 to the proper node and moved the R-4D HiPAT to the 1978 node. Will be in the RP-1 update.
