### ISSUE TITLE
Error on Plume direction.

### ISSUE THREAD

**Issue by pack7df** [KSP-RO/ROEngines#152]
![image](https://user-images.githubusercontent.com/16261753/148326544-8164db80-0010-4fef-bc76-d846fc416680.png)

The rocket is ROE-A4, upgraded as A-9.

I hope it helps.

Greetings.

UPDATE, I haven't update for ROEngines v1.10.1, I already noticed now.

**Comment by NathanKell** [comment]
Already fixed, update ROE. https://github.com/KSP-RO/ROEngines/releases/tag/v1.10.1.0

**Comment by NathanKell** [comment]
Misread, sorry.

**Comment by NathanKell** [comment]
Nope, I was right the first time, it's the same model even though the part ingame is different. Fixed in the latest version.
