### ISSUE TITLE
RD-180 gimbal breaks if the engine is rotated

### ISSUE THREAD

**Issue by Capkirk123** [KSP-RO/ROEngines#155]
If the RD-180 is rotated 90 (or 270) degrees about the roll axis from it's default rotation, the pitch and yaw gimbals stop working. This is probably due to some odd interaction with the multiple gimbal modules of the RD-180, since unlocking all gimbal axis allows it to work correctly again.

**Comment by al2me6** [comment]
Fixed by #158.
