### ISSUE TITLE
UA1207 nonfunctional

### ISSUE THREAD

**Issue by dgeastman** [KSP-RO/ROEngines#17]
The UA1207 does not indicate any dV and does not ignite upon staging.

**Comment by dgeastman** [comment]
I should perhaps clarify, this was on a vanilla 1.6.1 RO install from CKAN, no other parts packs such as BDB, RN, FASA, etc.  Just ROEngines.  Simple test of capsule, motor.  Every other SRM I tested works, but not the 1207.

**Comment by lukecologne** [comment]
It seems like the UA1207 from ROEngines is not throttle-locked like SRB's should be. Try to throttle up, it should ignite.

**Comment by dgeastman** [comment]
Nope, it has no fuel.  Which also explains why it shows no dV in the VAB or MechJeb displays.

**Comment by lukecologne** [comment]
Weird. For me, it has fuel by default. Did you load a premade rocket?

**Comment by dgeastman** [comment]
Nope, as I said above, new craft, capsule, UA1207.  Nothing more.
