### ISSUE TITLE
Multiple Engines miss Gimbal

### ISSUE THREAD

**Issue by fat-lobyte** [KSP-RO/ROEngines#19]
Several engines, like the NK-33 and NK-43 do not have a gimbal. This is because their `ModuleGimbal` is missing the `MODULE` keyword above the opening brace.

**Comment by Gordon-Dry** [comment]
Also RD8_RE.cfg

And many files have mixed tab intends and space intends, sometime the intends are not aligned etc.

**Comment by pap1723** [comment]
Fixed with https://github.com/KSP-RO/ROEngines/commit/7e9b079c0cdd80e411d77037a6dc88073e6db152
