### ISSUE TITLE
LR-91 Vernier causes unreasonable vehicle torque

### ISSUE THREAD

**Issue by eiWare** [KSP-RO/ROEngines#193]
Due to the offset and unreasonably large thrust of the vernier attachment on the LR-91, the vehicle torques excessively. Further, the vernier attached to the engine is not working.

Possible solutions would be:
- Remove the vernier from the LR-91 engine (or at least give an option to remove it)
- Make a separate vernier parts that can be rotated according to needs
- Reduce the thrust of the vernier attachment to reasonable levels

![Screenshot 2023-04-09 124920](https://user-images.githubusercontent.com/38304804/230785802-f943372a-4eda-4501-9f9f-b3c37c6d4688.jpg)

**Comment by marsh1832** [comment]
I’ve used this engine quite a lot and it always flies straight for me. Wait, if the vernier isn’t working, then how can it be applying excessive torque?

**Comment by eiWare** [comment]
Well... it is working, as a second engine with approximately the same thrust as the main LR-91, but offset to the side which is what is causing the torquing (see the attached RCS build aid diagram). 
It isn't working as to not gimbaling, therefore not providing roll control

**Comment by Capkirk123** [comment]
Cannot replicate, the vernier functions fine. Keep in mind, I don't believe the RCSBuildAid window correctly reports thrust of engines with multiple thrust transforms.

A known issue is that if you get the LR-91 from a subassembly, the vernier gimbal will break. Try replacing the LR91 with a new part, and make sure everything is fully up to date.

**Comment by eiWare** [comment]
Thanks, I'll check it out on a new build today. I'll let you know how it
goes.
Is there any debug info I should attach (apart from a screencap) if there
are still issues?

**Comment by Capkirk123** [comment]
Is there any further information on this, or can it be closed?
