### ISSUE TITLE
Modular RCS using SIVB APS 500 model is unresponsive

### ISSUE THREAD

**Issue by LuneoLucy** [KSP-RO/ROEngines#208]
Happens on express install, more models may have the same issue.

The RCS config looks normal in PAW but doesn't respond to any input

**Comment by RubenOllesch** [comment]
I'm having the exact same issue, the 500 version has no effect, while the earlier 200 model works just fine.
[modlist.txt](https://github.com/KSP-RO/ROEngines/files/12909622/modlist.txt)
