### ISSUE TITLE
RD-0105 Verniers should be separate parts instead of switching between models

### ISSUE THREAD

**Issue by ProtonEnjoyer** [KSP-RO/ROEngines#209]
I believe RD-0105 verniers should be separate instead of fixed to the engine, that way there's no need to switch between "Compact" and "Wide" vernier options.

I do not know if this suggestion is logical, I don't know if this issue makes sense to be posted, but if anyone could give feedback to this it'd be nice

**Comment by Capkirk123** [comment]
Yes, separate verniers cause many balance problems, especially pure gas generator verniers like the RD-0105, which cannot run at all if the main engine is not running. Until this is resolved, I will be avoiding adding separate vernier parts if possible.
