### ISSUE TITLE
RD-105/109 wide vernier setting is not wide enough

### ISSUE THREAD

**Issue by hallucinogender** [KSP-RO/ROEngines#212]
See [this issue](https://github.com/KSP-RO/ROEngines/issues/216) in the RP-1 repository; I forgot that ROEngines is a separate mod at the time I made the original issue.

**Comment by Capkirk123** [comment]
Resolved by https://github.com/KSP-RO/ROEngines/commit/b122c97e5b13f7acf484a89a43dee4259bb48826
