### ISSUE TITLE
RD-105/109 wide vernier setting is not wide enough

### ISSUE THREAD

**Issue by hallucinogender** [KSP-RO/ROEngines#216]
As the title says. The wide verniers *should* be wide enough to stick out of the sides of the Vostok upper stage, as demonstrated [here](https://en.wikipedia.org/wiki/Vostok_1#/media/File:Vostok_spacecraft.jpg).
![image](https://github.com/KSP-RO/RP-1/assets/107995536/fd6a1295-d1d4-4215-80bb-ad74071f2b00)

In reality, the wide verniers are just barely not wide enough to stick out of the sides of the spacecraft, as this screenshot demonstrates:
![image](https://github.com/KSP-RO/RP-1/assets/107995536/ebb31e40-4141-485d-b350-beec7f96298d)

**Comment by Capkirk123** [comment]
Resolved by https://github.com/KSP-RO/ROEngines/commit/b122c97e5b13f7acf484a89a43dee4259bb48826
