### ISSUE TITLE
XLR-99 Not Working

### ISSUE THREAD

**Issue by Sandrom191** [KSP-RO/ROEngines#224]
I'm not able to add fuel to tanks, and if I add then manually the engine doesn't fire
I have tried changing the type of tank, game save, and I've encountered the same problem
It seems that it's missing some stuff on the code side, It looks very different from the other engine archives (Btw, I don't know nothing about coding)
![2024-01-08 (1)](https://github.com/KSP-RO/ROEngines/assets/90786296/8f17a332-0115-48c1-8f3b-fe5c2884f1d1)

![2024-01-08](https://github.com/KSP-RO/ROEngines/assets/90786296/f55e5fa4-3393-4880-92d8-fe7cefa04faa)
 
 

https://github.com/KSP-RO/ROEngines/assets/90786296/a8c6b38c-6dfe-4996-93e1-61a3515dd9f3

**Comment by NovemberOrWhatever** [comment]
That engine looks borked. Try removing tweakscale and KSP recall? That certainly won't hurt

**Comment by Sandrom191** [comment]
Removed them and still got the same issue.
I'm thinking about upgrading to the latest version of ROengines (I currently have version 2.5.0.0), but the last time I updated my mods I lost my game save, Do you know if the engine is working in the latest version? Thanks for helping.
 @NovemberOrWhatever

**Comment by lpgagnon** [comment]
if you also have ROEnginesExtended, that would be the first thing to update https://github.com/Capkirk123/ROEngines-Extended/releases

**Comment by Sandrom191** [comment]
Yes, I'm going to try that, I was just now looking on ROenginesExtended github and the latest version has a fixed problem in the 
XLR-99 files.

**Comment by Sandrom191** [comment]
It's working now, Thank you so much guys!
