### ISSUE TITLE
RL-10C-X Does not appear in latest RO despite it being present in configs and tech level set

### ISSUE THREAD

**Issue by JovietUnion** [KSP-RO/ROEngines#226]
Here is a screenshot
![image](https://github.com/KSP-RO/RealismOverhaul/assets/62820134/c04fb5a1-815b-486f-a954-fdf2e7ee46d2)

**Comment by Capkirk123** [comment]
Resolved by https://github.com/KSP-RO/ROEngines/commit/411eac8e0a444d7f3d4ab0b62e124d1f31425608

**Comment by JovietUnion** [comment]
Should I make a new save file now that it's fixed? Because it still did not appear
