### ISSUE TITLE
not seeying RD-270M in game

### ISSUE THREAD

**Issue by mad-exotix** [KSP-RO/ROEngines#228]
Hello,
By searching on internet I discovered that you ad the RD-270/RD-270M but it's seems that the RD-270M does not appear in game, but the RD-270 is here.
So if someone could help me or simply tell me how to find it (is it a engine config or a part?), thanks.
I tried my best to try to make it appear,
I duplicate my KSP and clear all mod from the game data folder then install the Roengine mod and it's dependencies but the RD-270M was still not appearing.
So I've look inside the folder of the mod (Roengine) and open the CFG of the RD-270M and notice that there was nothing other than some tag. Then I downloaded the mod from github (previously used Ckan) and notice that in the github version of the mod, in the CFG files of the RD-270M there were actually something (part config etc idk) so i take the github version of the mod and place it at the place of the Ckan version of the mod but they were still nothing.
SO i am running out of idea to try making the RD-270M appear in my game, maybe the solution is simple and i am dumb, goodbye and have a nice day.

**Comment by mad-exotix** [comment]
CFG files of the RD-270M in the Ckan downloaded ROengine:
![image_2024-03-02_214559919](https://github.com/KSP-RO/ROEngines/assets/161975638/296a4e34-4e4e-4a0b-bce9-7ed32cb4c2f1)

**Comment by mad-exotix** [comment]
CFG files of the RD-270M in the github downloaded ROengine:
![Capture d'écran 2024-03-02 214336](https://github.com/KSP-RO/ROEngines/assets/161975638/a62d4be6-b3c9-449c-8c6c-3c5b9076302a)

**Comment by Capkirk123** [comment]
The RD-270M no longer exists as a separate part, it is a config for the RD-270

**Comment by mad-exotix** [comment]
I'm sorry for my misunderstanding, but I see only 2 config for the RD-270, the UDMH - NOS and the Kerolox config, not the CH-4 version.

**Comment by Capkirk123** [comment]
The speclevel must be set to "alt history" in the RO difficulty settings for the RD-270M config to appear.
