### ISSUE TITLE
agena XLR81 dV 

### ISSUE THREAD

**Issue by kjpg** [KSP-RO/ROEngines#231]
Using Agena XLR81.  MechJeb and FWIW Kerbal engineer report 5000+ m/s of deltaV.  When executing a node to go from LEO to geostationary apoapsis (~2500 m/s), the burn consumes 80% of the fuel, i.e. ~4000 m/s.  Seems like an engine issue, not mechjeb, since KER gives a similar capacity.

on a mac, with uptodate RO/RP-1 installed using CKAN. ROengines v2.7, RO v17.8, RP1 v3.6.1

thanks!

Christine

**Comment by Capkirk123** [comment]
This is most likely a staging issue. The root part is probably not on the stage payload, resulting in a much lower calculated dry mass. Show a screenshot of the craft with the root psrt highlighted and MJ deltaV window.

**Comment by kjpg** [comment]
good call. root part was  in the payload but  had upper stage RCSs staging early; dV became sensible when I moved them up. can't make sense of it, because that was only a few 100 DV but that was the solution

thanks for you time. 
christine
