### ISSUE TITLE
RD-0205/0212 Engine too wide

### ISSUE THREAD

**Issue by DyBev** [KSP-RO/ROEngines#243]
The engine is too wide to be fitted onto a 4.1m fuel tank (Tank diameter provided to you when selecting the "proton" option in the Select Diameter window), because of this decouplers collide with the engine when getting decoupled. You need a 4.8m diameter to stop the decoupler from colliding.

**Comment by Capkirk123** [comment]
This is intentional, the verniers are supposed to hang out over the edge of the tank. This might require some creative fairing use to make work. Or just use the version with independent verniers.
