### ISSUE TITLE
More engines from Niche Parts

### ISSUE THREAD

**Issue by karlack26** [KSP-RO/ROEngines#3]
https://forum.kerbalspaceprogram.com/index.php?/topic/144157-113-nicheparts-v142-real-engine-pack/ some more engines for you to consider pap. They all have RO configs most are RP-0 ready, the licence lets you use them, plus it adds more engines later to the tree.

**Comment by pap1723** [comment]
If you look at my Engine List sheet, you'll see they are included. :)

**Comment by karlack26** [comment]
lol my bad

**Comment by pap1723** [comment]
Not at all! I appreciate the ideas!

**Comment by karlack26** [comment]
I can go and fix those config issues I was asking about in discord for ya :) I guess starting my own repo with those fixed configs is the best course of action i could not find that mod on git hub ?

**Comment by pap1723** [comment]
So, probably because I am dumb, but I have actually been rewriting all config files. If you look St my repo you will see that. I have found for me that it is faster to do that than to try and find and replace any errors.

**Comment by karlack26** [comment]
makes sense, i just happened to stumble in to this error due to me using this mod in my current game and was curious about how to fix it.

**Comment by pap1723** [comment]
If you are interested in writing configs for these, I would MORE than welcome the help! If you look at a couple of the configs I wrote, you will see the structure I like to use and what is needed.

**Comment by karlack26** [comment]
https://github.com/karlack26/NicheParts-for-RO-Engines well here they are if you need them. warnings gone. Tested a few of them in game real-plume and smoke screen works. just as i was about to hit enter you posted that last message haha. Ya i will compare what your configs are to these but here they are anyways.

**Comment by karlack26** [comment]
Do you have like a config template that i can  just fill in the empty fields ? Also this mod contains lots of RCS engines parts is that beyond the scope of RO-Engines.

**Comment by karlack26** [comment]
Ok question about configs. Each engine in Nicheparts has 4 separate config file associated with it. One in the asset folder with the textures files and the mu files. Are these the stock configs ? are they needed in RO-engines.  I noticed some of the engines you have have configs in the asset folder some do not. 
 Then there is the RO-Configs in Niche parts I am assuming these configs are the one  i should be reformatting to fit to your way of laying out configs. 
Then there is 1 config file  with all of the engines fuel types and thrust curves.  which i am not seeing where they go in R0-engines or does this config need to be added to the suggested mods config folder of RO 
Real Plume configs i got figured out.
