### ISSUE TITLE
Make new release such that the Raptor Engine of SpaceX is usable too

### ISSUE THREAD

**Issue by realvictorprm** [KSP-RO/ROEngines#47]
Hi fellow engineers!

I just wanted to ask whether you could provide a new release which can be downloaded via CKAN to update the mod to the newest version which (so far my understanding) includes the raptor engine :)

**Comment by DRVeyl** [comment]
Good news: https://github.com/KSP-RO/ROEngines/releases/tag/v1.5
Bad news: We got a little ahead of things, and some of the changes mean the ROMods all now require ROLib.  For reasons, we cannot put ROLib onto CKAN for KSP 1.7.

ROLib is currently available on CKAN for KSP 1.8+.  The latest release of ROEngines should be indexed by CKAN soon, and once we resolve a minor issue with .netkan configuration files, will also correctly reference ROLib as a dependency.

You -can- use this release of ROEngines with the ROLib v0.4 pre-release for KSP 1.7.  At this time, ROEngines contains only .cfg files, and all of the supporting code is in ROLib.

**Comment by realvictorprm** [comment]
Nice. Thanks for the clarification!

DRVeyl <notifications@github.com> schrieb am So., 5. Apr. 2020, 21:56:
