### ISSUE TITLE
ROE-GCRC solid booster's throttle can be cut

### ISSUE THREAD

**Issue by rsparkyc** [KSP-RO/ROEngines#53]
Even though this engine says it cannot be shut down, I am still able to shut it down in flight (and thus restart it) by killing my throttle. This is the only solid that I've seen this behaviour on.

**Comment by rsparkyc** [comment]
Actually, looks like i see this on the baby sergant too, but I can confirm that I see the correct behavior on the Castor 1

**Comment by lpgagnon** [comment]
https://discordapp.com/channels/319857228905447436/319857228905447436/601791897924665346

**Comment by rsparkyc** [comment]
I think what we're missing is the throttleLocked flag

**Comment by rsparkyc** [comment]
ahh, should have checked the discord...but at least we have a ticket now for it.

**Comment by rsparkyc** [comment]
Addressing this in RealismOverhaul with this PR: https://github.com/KSP-RO/RealismOverhaul/pull/2226
