### ISSUE TITLE
ROE-RS68 Engine Missing Mass In ROEngines/PartConfigs/RS68_SSTU.cfg

### ISSUE THREAD

**Issue by titanin** [KSP-RO/ROEngines#58]
Module Manager is throwing an Error with SMURFF patches

> [LOG 16:43:09.154] Applying update SMURFF/SMURFF/@PART[*]:HAS[@RESOURCE[Ablator],~SMURFFExclude[*rue]]:FOR[zzz_SMURFF] to ROEngines/PartConfigs/RS68_SSTU.cfg/PART[ROE-RS68]
[WRN 16:43:09.155] Cannot find key mass in PART
[ERR 16:43:09.155] Error - Cannot parse variable search when replacing (%) key initialmass = #$mass$

Not sure if the Engines a are supposed to have an ablator and are supposed to have no mass? Also what mass are they supposed to have before or without SMURFF?

**Comment by titanin** [comment]
Okay this is a whole mess. If you want you can have my MMpatch log as I was looking through it searching for all instances with the engine config it seems maybe RealPlumes ore someone else is patching the engine to have an ablator but not assigning a mass, as SMURFF is the last one to apply patches to the configs. I just dont know how to ask or inform then :(

**Comment by lukecologne** [comment]
ROEngines does not support SMURFF. It relies on ROs engine configs to configure the engine modules.

**Comment by DRVeyl** [comment]
Do I need to edit the .netkan to explicitly depend on RealismOverhaul?  I was trying to avoid that where I could in the ROMods, but the Engine configs are maybe _too_ integrated.

**Comment by titanin** [comment]
Thanks for the help guys. Now I know that both mods are not compatible :)
