### ISSUE TITLE
LR91 not working

### ISSUE THREAD

**Issue by DocRockwell** [KSP-RO/ROEngines#6]
The engine configs don't seem to initialize properly.

**Comment by pap1723** [comment]
Ah, these need the new changes I made for Realism Overhaul Global Engines.
I have to wait to push it until I can change the other LR91 engines. I
didn't notice it because my local branch had those changes. Thanks for
reporting! I will hurry those changes in.

**Comment by pap1723** [comment]
Fixed with the newest commit from RealismOverhaul
