### ISSUE TITLE
Include SSTU Engine-merging capability

### ISSUE THREAD

**Issue by Kerbinator-Fras** [KSP-RO/ROEngines#61]
**In ROEngines the SSTU engines does are not as good as like original SSTU ones since they don't have tweakable mounts,engine cluster amount and a bunch of other varibles.**
SSTU's engine-merging capability is truly amazing,as it make construction of heavy rockets much easier and also more beautiful(despite an unscientific point that SSTU engine mounts are massless no matter what size it is). However it is blocked by PatchManager of ROEngines, _so I have to delete the PatchManager  of ROEngines as a temporary choice_ :-( (the PM GUI also not work since I installed KSPIE and cannot open the ROEngines branch button.)
**Another and much better solution is to use non-SSTU engine just meshes and introduce SSTU engine-merging capabilities and mounts to ALL engines.** {highly recommended! for further development)(consider add mass of engine mount depend on engine cluster amount and type)
Also @shadowmage45 for this issue, looking forward to a happy RO collaborations!
I also love ROEngines since it is well-maintained (unlike REP abandoned in 1.3.1) and its most complete engine sets, fully RO-competatible and bugless.

**Comment by Amperzand** [comment]
The SSTU engine-clustering feature isn't included because, among other things, it treats the engines as a single part, which means that engine failures would cause all engines in the cluster to fail simultaneously.
