### ISSUE TITLE
Normalize Cost for non-RP situations [Bonus]

### ISSUE THREAD

**Issue by Kerbinator-CN** [KSP-RO/ROEngines#62]
Well I'm _not_ playing realistic progression now
However I sincerely hope that you can n**ormalize RO Engines cost to a proper level** (same as RP-1 is OK)
The cost problem has already been highly problematic in a bunch of engine packs like RealEngines pack,one part of the ROEngines.
That's because cost of most _other_ parts are correct,but **as for engines, they are highly incorrect** for non-RP players :-(

**Comment by Kerbinator-CN** [comment]
Note: Not very necessary
but indeed a bonus :)

**Comment by DRVeyl** [comment]
I don't see this happening.  Inside sandbox, cost is irrelevant.  In a career, it's up to that sort of career system to balance its rewards and its part costs.  ROEngines is largely an accumulation of parts from multiple mod sources, and tries to address part bloat in the VAB.  There's no practical way we will keep up with any cost updates/changes from the original sources, and there's really no expectation that someone is using ROEngines in a career that isn't RP-1.  Or the expectation is that career system will adjust prices of ROEngines and everything else as it needs.
