### ISSUE TITLE
RemoveEngines nukes the SSTU Apollo Service module

### ISSUE THREAD

**Issue by DocRockwell** [KSP-RO/ROEngines#8]
Also kind of related, but what do you think about leaving the SSTU RD-107 and RD-108 parts in? They have really nice fairings, and an R-7 just isn't an R7 without the engine fairings.

**Comment by MikeOnTea** [comment]
ROEngines uses the RD-107 and RD-108 from SSTU.

**Comment by pap1723** [comment]
I will fix the Service Module, thanks!!
As for the RD-107 and RD-108, are you referring to the boattails / mounts they are in? The ones in ROE are from SSTU, just with those mounts removed.

**Comment by DocRockwell** [comment]
Yeah I realize they use the SSTU engine models, is there anyway to keep the mounts? It's not a big deal, I just think the mounts are a really nice features, and I ended up adding back the SSTU RD107/108 parts to use them.

**Comment by pap1723** [comment]
Maybe it would be worth it to add the mounts as separate parts...?
Other than the RD-10x mounts, which should be included?

**Comment by DocRockwell** [comment]
The rd-10x mounts are the only ones that come to mind, all the other SSTU mounts can be found on the tanks.

**Comment by pap1723** [comment]
Fixed with the Mounts included as well. TU Coloring to come Soon(TM)
