### ISSUE TITLE
Gamma 2 Engine Stats off

### ISSUE THREAD

**Issue by FrisbeeDriver** [KSP-RO/ROEngines#90]
I came across a source that would seem to indicate that the Gamma 2 engine stats are a little off.  http://www.astronautix.com/g/gamma2.html seems to imply that the burn time should be 113s not 140s and that the ISP should be 265 (vac) 251(sea level) rather than the 267(vac)/ 189 (sea level).  All the other engine stats seem to be pretty much bang on with this data source.

**Comment by Capkirk123** [comment]
1.) Astronautix is generally a pretty bad source. Unless you can find more sources to back it up (which don’t cite astronautix as their source too), don’t trust it.

2.) ROEngines does not configure the Gamma 2, or any engine for that matter. All engine configs are handled by RO.

**Comment by FrisbeeDriver** [comment]
Good to know on both counts.

**Comment by NathanKell** [comment]
For the record, the astronautix stats are not plausible since the Gamma 2
explicitly got larger, vacuum-optimized nozzles vs. the Gamma 8, and so it
beggars belief they would have the same performance.
