### ISSUE TITLE
RL10 nozzle is always extended

### ISSUE THREAD

**Issue by JV-Fernandes** [KSP-RO/ROEngines#92]
I'm having some trouble with the rl10 engines nozzle extension. When i select the engine on the VAB, the nozzle is already extended, i was expecting that they will only extend after activating...

**Comment by Capkirk123** [comment]
You are missing ROLib (either it’s not installed at all, or you installed the master instead of the release)

**Comment by JV-Fernandes** [comment]
I have the master installed. Should i install both, the master and the release? or just the release?

**Comment by Capkirk123** [comment]
Delete it, and install the release

**Comment by JV-Fernandes** [comment]
I tried this but it still don't work... https://github.com/KSP-RO/ROLibrary/releases/tag/v1.1 I installed this version of ROlib, it's right?

**Comment by DRVeyl** [comment]
Some of this functionality was moved back from ROLib to ROEngines.  (We're starting down the path of removing module-specific code from the library: it doesn't make sense to update ROLib 10 times for ROTanks patches when you only use ROSolar.)  That process may be messy.

<https://github.com/KSP-RO/ROEngines/commit/7895ca433e6799b3fb366771689fc5cf10d1cbc7> moved this to ROE.

This probably works with the master branch of ROE after that commit, and a corresponding release of ROLib.  I'm preparing a ROE release now, and things are working.
